### ISSUE TITLE
Docker container usage

### ISSUE THREAD

**Issue by cgg507** [filiparag/hetzner_ddns#16]
Hey @filiparag awesome job with this script, it's been very helpful to keep my ISP-provided dynamic addresses synced to Hetzner DDNS service for a while now.

I know the systemctl-based script works flawlessly in other setups I have, but today I decided to give the Docker image a try (based on the usage line located in https://hub.docker.com/r/filiparag/hetzner_ddns)

I noticed the following behavior, which I gotta apologize beforehand if this is working as designed, even though I have a strong feeling it is not.

1. Is this expected to be run as one-shot? Reason I'm asking is if I close the terminal in which the docker was started, the container would exit from docker engine perspective.

2. Is it expected to post the docker logs directly into the terminal it is started from? 

3. If I stop the container using a second terminal, and then "docker start" it, no logs are seen in the terminal and it behaves as a normal docker, returning to the shell prompt. Also, it keep updating the ip address as expected.

Docker version
```
root@dock:/opt/scripts# docker -v
Docker version 27.3.1, build ce12230
```

Ran container from terminal, it does not return the shell prompt, and would post all docker logs into terminal console.

![image](https://github.com/user-attachments/assets/a3134350-722d-4c14-82c5-3ad548d20edf)

hetzner_ddns.conf contents

![image](https://github.com/user-attachments/assets/6440804d-8862-4a51-9c11-bf4f9d53b497)

Any help or guidance would be appreciated.

**Comment by filiparag** [comment]
Hi, thanks for opening the issue. To answer your questions:

If you run it without the `--detach` flag, the container shall terminate when the parent (shell) does, and outputs the logs to standard output (active console window). When you stopped and started the container manually, you inadvertently caused it to detach.
