### ISSUE TITLE
Feature request: Option to disable update of IPv6 record.

### ISSUE THREAD

**Issue by Christophe999s** [filiparag/hetzner_ddns#19]
First of all, thanks for your work and making this available for all of us.

In my case, the IPv6 record that is used to update the AAAA record isn't correct.
Since I've configured a static record,I don't want it to change.

As a workaround I've created an IPv4 only network in docker, but the logs keep showing an error:
Warning: Unable to fetch previous IPv6 address for my.domain.com
An option to disable the AAA record would be a nice feature.

**Comment by Christophe999s** [comment]
Prefix is indeed correct.
The correct IPv6 is ending on be24:11ff:feec:9052, but it updates using ::2000
curl -6 https://ipv6.icanhazip.com also returns the ::2000 address
![image](https://github.com/user-attachments/assets/f1eee074-d46f-4394-91c6-93bd59487ddd)

**Comment by filiparag** [comment]
Right, that can be expected when running on a machine with multiple egress addresses ([read more about it here](https://www.akkadia.org/drepper/linux-rfc3484.html)).

Anyway, I'm thinking of adding something along the line of the following [configuration](https://github.com/filiparag/hetzner_ddns/blob/master/hetzner_ddns.conf) parameters:
```ini
ipv4=true
ipv6=false
```

Would this resolve your problem?

**Comment by Christophe999s** [comment]
yes, that's perfect

**Comment by filiparag** [comment]
Okay, I will add the feature as soon as I can.

**Comment by filiparag** [comment]
You can download the new version [0.2.6](https://github.com/filiparag/hetzner_ddns/releases/tag/0.2.6) with this feature.
