### ISSUE TITLE
Wildcard subdomains unexpeted expansion

### ISSUE THREAD

**Issue by capocasa** [filiparag/hetzner_ddns#2]
Couldn't quite figure out where it happens but the wildcard subdomain seems to be receiving a shell expanseion somewhere.

Placed "@ *" into records variable. Debian 11.2

[2022-11-16 15:30:29] Missing both records for bin.example.org
[2022-11-16 15:30:29] Missing both records for boot.example.org
[2022-11-16 15:30:30] Missing both records for dev.example.org
...

It seems that the asterisk is being expanded to the files in the root directory somewhere, but I couldn't figure it out- the obvious contenders are taken care of (no missing double quotes i could find...)

**Comment by filiparag** [comment]
Bug should be fixed in [09236f7](https://github.com/filiparag/hetzner_ddns/tree/09236f737d2f1b534e40481a3bfb818605256218 ). Please confirm if it resolves your issue.

**Comment by capocasa** [comment]
Works like a charm! Thanks a lot!!!

**Comment by capocasa** [comment]
Very nice work on the tool, by the way, appreciate the effort to polish it. Makes you feel right at home in neo unix land.
