### ISSUE TITLE
Use ip.hetzner.com instead of Akamai

### ISSUE THREAD

**Issue by thenktor** [filiparag/hetzner_ddns#4]
Hi,

maybe it"s a goog idea to retrieve IP from Hetzner instead of Akamai. This would remove dependency to a third party:
`curl -4 https://ip.hetzner.com` and `curl -6 https://ip.hetzner.com`

See also https://ip.hetzner.com/

**Comment by filiparag** [comment]
I wasn't aware of this service by Hetzner. Thanks for pointing it out!

**Comment by filiparag** [comment]
Added in commit [aabb7f6](https://github.com/filiparag/hetzner_ddns/commit/aabb7f6b3dd4ea59d718d5c0b7dfef91e2fedcc8).
