### ISSUE TITLE
With --daemon argument config file cannot be found

### ISSUE THREAD

**Issue by thenktor** [filiparag/hetzner_ddns#5]
Hi,

when started with daemon argument, the config file cannot be found because it wants to open `/usr/local/etc/hetzner_ddns.--daemon.conf`.

**Comment by filiparag** [comment]
Hi, thanks for reporting this bug. It was introduced in [this](https://github.com/filiparag/hetzner_ddns/blob/68b8a2a20a8bc7a08284a114e0581fc021576926/hetzner_ddns.sh) commit.

**Comment by filiparag** [comment]
Should be fixed in commit [8fd7780](https://github.com/filiparag/hetzner_ddns/commit/8fd77807913133714b370ed94d328ea1a685c723).  
Please try it and report back.
