### ISSUE TITLE
Package repos are not containing 0.2.3

### ISSUE THREAD

**Issue by waschinski** [filiparag/hetzner_ddns#8]
I just checked copr and it's still showing 0.2.2-1.fc34 from 1y 5m ago. Seems other repos are also outdated.

**Comment by filiparag** [comment]
I was waiting for [another issue](https://github.com/filiparag/hetzner_ddns/issues/5#issuecomment-1439052593) to be closed, but it seems to have become stale.

I will update the repos once I have some free time. Version `0.2.2` has a bug mentioned in that issue, but it should't affect most use-cases.

**Comment by waschinski** [comment]
Alright, thanks for going to look at it. Meanwhile 0.2.2 seems to be working fine, it's just dnf bugging about it being outdated (fc36 on fc38).

**Comment by filiparag** [comment]
New version [`0.2.4`](https://github.com/filiparag/hetzner_ddns/releases/tag/0.2.4) has been added to COPR, so I am closing this issue.
